#!/bin/bash
echo Italiano
read var
lang=$(xset -q|grep LED| awk '{ print $10 }')
if [ "$lang" != 00001000 ] ; then
trans it:it -speak $var  > /dev/null 2>&1 # - озчучка trans, онлайн
printf "%s\t%s\n" "$var" "$(trans -brief :it "$var")" >> ~/sn/it.txt # - история
sdcv -ucn "Universal (It-Ru)" --utf8-output --color "$var" | less -R 

else
trans it:it -speak $(trans -brief :it "$var") > /dev/null 2>&1
sdcv -ucn "Universal (Ru-It)" --utf8-output --color "$var" | less -R
fi
clear
sdi

###
Если определение раскладки не работает, проверь значение LED в выводе xset -q





