#!/bin/bash
read var
lang=$(xset -q|grep LED| awk '{ print $10 }')
if [ "$lang" != 00001000 ] ; then
trans -speak $var  > /dev/null 2>&1 # - озчучка trans, онлайн
printf "%s\t%s\n" "$var" "$(trans -brief :ru "$var")" >> ~/sn/en.txt # - история
sdcv -ucn "LingvoUniversal (En-Ru)" --utf8-output --color "$var" | less -R 

else
sdcv -ucn "LingvoUniversal (Ru-En)" --utf8-output --color "$var" | less -R 
fi
clear
sd

###
mpv $(find /mnt/drive_1_0/linux/soft/dict/Sound_En -name $var.wav) # > /dev/null 2>&1 # озвучка

