#!/bin/bash
echo Deutsch
read var
lang=$(xset -q|grep LED| awk '{ print $10 }')
if [ "$lang" != 00001000 ] ; then
trans de:de -speak $var  > /dev/null 2>&1 # - озчучка trans, онлайн
printf "%s\t%s\n" "$var" "$(trans -brief :it "$var")" >> ~/sn/de.txt # - история
sdcv -ucn "Universal (De-Ru)" --utf8-output --color "$var" | less -R 

else
trans de:de -speak $(trans -brief :de "$var") > /dev/null 2>&1
sdcv -ucn "Universal (Ru-De)" --utf8-output --color "$var" | less -R
fi
clear
sdd

###
Если определение раскладки не работает, проверь значение LED в выводе xset -q
