export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"

export ZDOTDIR="$HOME/.config/zsh"
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export PYENV_ROOT=$XDG_DATA_HOME/pyenv

export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority

export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export STARDICT_DATA_DIR="$HOME/data/soft/stardict-dicts/dic"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export FZF_MARKS_FILE="$HOME/.config/ranger/fzf-marks"

export IPFS_PATH="$XDG_DATA_HOME"/ipfs
export PYTHON_HISTORY=$XDG_STATE_HOME/python_history
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
