#!/bin/bash
Green='\033[0;32m'
Col_off='\033[0m'

# Переход в каталог с пакетами AUR
cd ~/builds/aur
# Проверка каждого пакета
for package in */; do
  cd "$package"
  echo -e "${Green}$package${Col_off}"
  git pull | grep date || makepkg -si --noconfirm
  cd ..
done
echo -e "${Green}Обновления завершены."