#!/bin/bash
#dependency: axel, wget, fzf.
alpha_update(){
nc=2 # number of connections
# dependency check and blender download
fzf --version > /dev/null 2>&1 || echo "missing dependency: fzf - command-line fuzzy finder."
axel -V > /dev/null 2>&1 || echo "missing dependency: axel - light command line download accelerator"
wget --version > /dev/null 2>&1 || echo "missing dependency: wget - the non-interactive network downloader."
ls -l ~/builds/blender/downloads/alpha/ > /dev/null 2>&1 || mkdir -p ~/builds/blender/downloads/alpha/
rm -r ~/builds/blender/downloads/alpha/* > /dev/null 2>&1
cd ~/builds/blender/downloads/alpha/
var=$(wget -qO- https://builder.blender.org/download/daily/ | grep -o -G 'blender-[^a-z]*-alpha+main.[0-9a-z]*-linux.x86_64-release.tar.xz' | awk 'NR==1')
axel -n $nc https://builder.blender.org/download/daily/$var
# sha256sum check
axel -n $nc https://builder.blender.org/download/daily/$var.sha256
echo $(cat $var.sha256) $var > $var.sha256
sha256sum -c $var.sha256 || echo "sha256sum corrupt!" > log_sha
# blender extract
tar -xf ~/builds/blender/downloads/alpha/*.tar.xz -C ~/builds/blender/downloads/alpha
# icon
bl_path="$(find ~/builds/blender/downloads/alpha/* -maxdepth 1 -name 'blender' | head -1)"
echo $bl_path
sed -i '/Exec/d' "$bl_path.desktop"
sed -i '/Icon/d' "$bl_path.desktop"
sed -i '/Name/d' "$bl_path.desktop"
echo "Exec=$bl_path" %f >> $bl_path.desktop
echo "Icon=$bl_path.svg" >> $bl_path.desktop
echo "Name=blender_alpha_snark" >> $bl_path.desktop
cp "$bl_path.desktop" ~/.local/share/applications/blender_alpha_snark.desktop
}
blender_update(){
nc=6 # number of connections
# dependency check and blender download
fzf --version > /dev/null 2>&1 || echo "missing dependency: fzf - command-line fuzzy finder."
axel -V > /dev/null 2>&1 || echo "missing dependency: axel - light command line download accelerator"
wget --version > /dev/null 2>&1 || echo "missing dependency: wget - the non-interactive network downloader."
ls -l ~/builds/blender/downloads/blender/ > /dev/null 2>&1 || mkdir -p ~/builds/blender/downloads/blender/
rm -r ~/builds/blender/downloads/blender/* > /dev/null 2>&1
cd ~/builds/blender/downloads/blender/
ver=$(wget -qO- https://ftp.halifax.rwth-aachen.de/blender/release/ |  grep -o -G 'Blender[0-9].[0-9]' | tail -1)
ver2=$(wget -qO- https://ftp.halifax.rwth-aachen.de/blender/release/$ver |  grep -o -G 'blender-[0-9].[0-9].[0-9]-linux-x64.tar.xz' | tail -1)
axel -n $nc https://ftp.halifax.rwth-aachen.de/blender/release/$ver/$ver2
# sha256sum check
#axel -n $nc https://ftp.halifax.rwth-aachen.de/blender/release/$ver/*.sha256
#sha256sum -c *.sha256 | grep OK || echo "sha256sum corrupt!" > log_sha
# blender extract
tar -xf ~/builds/blender/downloads/blender/*.tar.xz -C ~/builds/blender/downloads/blender
# icon
bl_path="$(find ~/builds/blender/downloads/blender/* -maxdepth 1 -name 'blender' | head -1)"
echo $bl_path
sed -i '/Exec/d' "$bl_path.desktop"
sed -i '/Icon/d' "$bl_path.desktop"
sed -i '/Name/d' "$bl_path.desktop"
echo "Exec=$bl_path" %f >> $bl_path.desktop
echo "Icon=$bl_path.svg" >> $bl_path.desktop
echo "Name=blender_snark" >> $bl_path.desktop
cp "$bl_path.desktop" ~/.local/share/applications/blender_snark.desktop
}
run="$(echo -e "alpha_update\nblender_update" | fzf )"
$run



